version: '3'

volumes:
  dbForZeldaPost:
#   fold:
#   dbForPost:

networks: 
    net:
      driver: bridge

services:
  zelda-cookbook-backend:
    build: ./zelda_b
    ports:
      - "3000:3000"
    networks: 
      - net
    depends_on: 
      - "db"
    # volumes:
    #   - "fold:/var/www/gutendex/static-root/"

  zelda-cookbook-frontend:
    build: ./zelda_f
    depends_on: 
      - "zelda-cookbook-backend"
    ports:
      - "3001:3000"
    networks: 
      - net


  db:
    image: postgres
    
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=zelda_cookbook"
    networks: 
      - net
    ports:
      - "81:5432"
    volumes:
      - "dbForZeldaPost:/var/lib/postgresql/data"
    


  nginx:
    build: ./nginx
    depends_on: 
      - "zelda-cookbook-frontend"
    ports: 
      - "80:80"
    networks: 
      - net
    # volumes:
    #   - "/home/bynet09/Desktop/exam2/nginx.conf:/etc/nginx/nginx.conf"
    #   - "/home/bynet09/Desktop/exam2/project/static:/usr/share/nginx/html"

#   log:
#     image:
#     networks: 
#       - net
      

